// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: covid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	"fmt"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CovidData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location     string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Age          string `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	InfectedType string `protobuf:"bytes,4,opt,name=infected_type,json=infectedType,proto3" json:"infected_type,omitempty"`
	State        string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *CovidData) Reset() {
	*x = CovidData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_covid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CovidData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CovidData) ProtoMessage() {}

func (x *CovidData) ProtoReflect() protoreflect.Message {
	mi := &file_covid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CovidData.ProtoReflect.Descriptor instead.
func (*CovidData) Descriptor() ([]byte, []int) {
	return file_covid_proto_rawDescGZIP(), []int{0}
}

func (x *CovidData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CovidData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CovidData) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *CovidData) GetInfectedType() string {
	if x != nil {
		return x.InfectedType
	}
	return ""
}

func (x *CovidData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_covid_proto protoreflect.FileDescriptor

var file_covid_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x66,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32,
	0x43, 0x0a, 0x0c, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x33, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_covid_proto_rawDescOnce sync.Once
	file_covid_proto_rawDescData = file_covid_proto_rawDesc
)

func file_covid_proto_rawDescGZIP() []byte {
	file_covid_proto_rawDescOnce.Do(func() {
		file_covid_proto_rawDescData = protoimpl.X.CompressGZIP(file_covid_proto_rawDescData)
	})
	return file_covid_proto_rawDescData
}

var file_covid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_covid_proto_goTypes = []interface{}{
	(*CovidData)(nil), // 0: proto.CovidData
}
var file_covid_proto_depIdxs = []int32{
	0, // 0: proto.CovidService.HandlerData:input_type -> proto.CovidData
	0, // 1: proto.CovidService.HandlerData:output_type -> proto.CovidData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_covid_proto_init() }
func file_covid_proto_init() {
	if File_covid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_covid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CovidData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_covid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_covid_proto_goTypes,
		DependencyIndexes: file_covid_proto_depIdxs,
		MessageInfos:      file_covid_proto_msgTypes,
	}.Build()
	File_covid_proto = out.File
	file_covid_proto_rawDesc = nil
	file_covid_proto_goTypes = nil
	file_covid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CovidServiceClient is the client API for CovidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CovidServiceClient interface {
	HandlerData(ctx context.Context, in *CovidData, opts ...grpc.CallOption) (*CovidData, error)
}

type covidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCovidServiceClient(cc grpc.ClientConnInterface) CovidServiceClient {
	return &covidServiceClient{cc}
}

func (c *covidServiceClient) HandlerData(ctx context.Context, in *CovidData, opts ...grpc.CallOption) (*CovidData, error) {
	out := new(CovidData)
	err := c.cc.Invoke(ctx, "/proto.CovidService/HandlerData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CovidServiceServer is the server API for CovidService service.
type CovidServiceServer interface {
	HandlerData(context.Context, *CovidData) (*CovidData, error)
}

// UnimplementedCovidServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCovidServiceServer struct {
}

func (*UnimplementedCovidServiceServer) HandlerData(context.Context, *CovidData) (*CovidData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlerData not implemented")
}

func RegisterCovidServiceServer(s *grpc.Server, srv CovidServiceServer) {
	s.RegisterService(&_CovidService_serviceDesc, srv)
}

func _CovidService_HandlerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	fmt.Println(srv, ctx)
	in := new(CovidData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CovidServiceServer).HandlerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CovidService/HandlerData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CovidServiceServer).HandlerData(ctx, req.(*CovidData))
	}
	return interceptor(ctx, in, info, handler)
}

var _CovidService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CovidService",
	HandlerType: (*CovidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlerData",
			Handler:    _CovidService_HandlerData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "covid.proto",
}
