// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: covid.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location     string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Age          int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Infectedtype string `protobuf:"bytes,4,opt,name=infectedtype,proto3" json:"infectedtype,omitempty"`
	State        string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ReqData) Reset() {
	*x = ReqData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_covid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqData) ProtoMessage() {}

func (x *ReqData) ProtoReflect() protoreflect.Message {
	mi := &file_covid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqData.ProtoReflect.Descriptor instead.
func (*ReqData) Descriptor() ([]byte, []int) {
	return file_covid_proto_rawDescGZIP(), []int{0}
}

func (x *ReqData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ReqData) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ReqData) GetInfectedtype() string {
	if x != nil {
		return x.Infectedtype
	}
	return ""
}

func (x *ReqData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ResData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location     string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Age          int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Infectedtype string `protobuf:"bytes,4,opt,name=infectedtype,proto3" json:"infectedtype,omitempty"`
	State        string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Way          string `protobuf:"bytes,6,opt,name=way,proto3" json:"way,omitempty"`
}

func (x *ResData) Reset() {
	*x = ResData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_covid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResData) ProtoMessage() {}

func (x *ResData) ProtoReflect() protoreflect.Message {
	mi := &file_covid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResData.ProtoReflect.Descriptor instead.
func (*ResData) Descriptor() ([]byte, []int) {
	return file_covid_proto_rawDescGZIP(), []int{1}
}

func (x *ResData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ResData) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ResData) GetInfectedtype() string {
	if x != nil {
		return x.Infectedtype
	}
	return ""
}

func (x *ResData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResData) GetWay() string {
	if x != nil {
		return x.Way
	}
	return ""
}

var File_covid_proto protoreflect.FileDescriptor

var file_covid_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x66,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x69, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x77, 0x61, 0x79, 0x32, 0x3d, 0x0a, 0x0c, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_covid_proto_rawDescOnce sync.Once
	file_covid_proto_rawDescData = file_covid_proto_rawDesc
)

func file_covid_proto_rawDescGZIP() []byte {
	file_covid_proto_rawDescOnce.Do(func() {
		file_covid_proto_rawDescData = protoimpl.X.CompressGZIP(file_covid_proto_rawDescData)
	})
	return file_covid_proto_rawDescData
}

var file_covid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_covid_proto_goTypes = []interface{}{
	(*ReqData)(nil), // 0: grpc.ReqData
	(*ResData)(nil), // 1: grpc.ResData
}
var file_covid_proto_depIdxs = []int32{
	0, // 0: grpc.covidService.handlerData:input_type -> grpc.ReqData
	1, // 1: grpc.covidService.handlerData:output_type -> grpc.ResData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_covid_proto_init() }
func file_covid_proto_init() {
	if File_covid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_covid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_covid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_covid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_covid_proto_goTypes,
		DependencyIndexes: file_covid_proto_depIdxs,
		MessageInfos:      file_covid_proto_msgTypes,
	}.Build()
	File_covid_proto = out.File
	file_covid_proto_rawDesc = nil
	file_covid_proto_goTypes = nil
	file_covid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CovidServiceClient is the client API for CovidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CovidServiceClient interface {
	HandlerData(ctx context.Context, in *ReqData, opts ...grpc.CallOption) (*ResData, error)
}

type covidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCovidServiceClient(cc grpc.ClientConnInterface) CovidServiceClient {
	return &covidServiceClient{cc}
}

func (c *covidServiceClient) HandlerData(ctx context.Context, in *ReqData, opts ...grpc.CallOption) (*ResData, error) {
	out := new(ResData)
	err := c.cc.Invoke(ctx, "/grpc.covidService/handlerData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CovidServiceServer is the server API for CovidService service.
type CovidServiceServer interface {
	HandlerData(context.Context, *ReqData) (*ResData, error)
}

// UnimplementedCovidServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCovidServiceServer struct {
}

func (*UnimplementedCovidServiceServer) HandlerData(context.Context, *ReqData) (*ResData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlerData not implemented")
}

func RegisterCovidServiceServer(s *grpc.Server, srv CovidServiceServer) {
	s.RegisterService(&_CovidService_serviceDesc, srv)
}

func _CovidService_HandlerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CovidServiceServer).HandlerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.covidService/HandlerData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CovidServiceServer).HandlerData(ctx, req.(*ReqData))
	}
	return interceptor(ctx, in, info, handler)
}

var _CovidService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.covidService",
	HandlerType: (*CovidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "handlerData",
			Handler:    _CovidService_HandlerData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "covid.proto",
}
