version: "3.3"
services:
  server-rmq:
      image : rabbitmq:3-management
      ports: 
          - "5672:5672"
          - "15672:15672"
      networks: 
        - RabbitMQ
  publisher-rmq:
      build: ./publisher
      restart: on-failure
      ports:
        - "4000:3000"
      depends_on:
        - server-rmq
      networks:
        - RabbitMQ
  consumer-rmq:
      build: ./consumer
      restart: on-failure
      depends_on:
        - server-rmq
      networks: 
        - RabbitMQ
networks: 
  RabbitMQ:
    driver: bridge
