  
version: "3.3"
services:

  grpc-client:
      build: ./client
      ports:
        - "4000:4000"
      networks: 
        - gRPC

  grpc-server:
      build: ./server
      networks: 
        - gRPC
networks: 
  gRPC:
    driver: bridge
    