
version: "3.3"
services:
  publisher-pubsub:
    build: ./publisher
    restart: on-failure
    ports:
      - "4000:4000"
    networks: 
      - PubSub
  subscriber-pubsub:
    build: ./subscriber
    restart: on-failure
    networks: 
      - PubSub
networks: 
  PubSub:
    driver: bridge
